CREATE TABLE IF NOT EXISTS movies (
	cache_key TEXT PRIMARY KEY,
	tmdb_id INTEGER NOT NULL,
	data TEXT NOT NULL,
	fetched_at INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS misses (
	cache_key TEXT PRIMARY KEY,
	fetched_at INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS related (
	tmdb_id INTEGER PRIMARY KEY,
	data TEXT NOT NULL,
	fetched_at INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS omdb (
	imdb_id TEXT PRIMARY KEY,
	data TEXT NOT NULL,
	fetched_at INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS omdb_misses (
	imdb_id TEXT PRIMARY KEY,
	fetched_at INTEGER NOT NULL
);
DROP TABLE IF EXISTS trakt_related;
